In [1]:
pip install ibm_quantum_widgets

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement ibm_quantum_widgets (from versions: none)
ERROR: No matching distribution found for ibm_quantum_widgets


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [3]:
# General Imports
import numpy as np

# Visualisation Imports
import matplotlib.pyplot as plt

# Scikit Imports
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler



In [4]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Hp\\Documents\\heart_disease_health_indicators_BRFSS2015.csv")
df.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  ...  AnyHealthcare  NoDocbcCost  GenHlth  \
0       0.0           0.0     0.0  ...            1.0          0.0      5.0   
1       0.0           1.0     0.0  ...            0.0          1.0      3.0   
2       0.0           0.0     1.0  ...            1.0          1.0      5.0   
3       0.0           1.0     1.0  ...            1.0          0.0      2.0   
4       0.0           1.0     1.0  ...            1.0          0.0      2.0   

   MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
0      18.0      15.0       1.0  0.0   9.0        4.0     3.0  
1       0.0       0.0       0.0  0.0   7.0        6.0     1.0  
2      30.0      30.0       1.0  0.0   9.0        4.0     8.0  
3       0.0       0.0       0.0  0.0  11.0        3.0     6.0  
4       3.0       0.0       0.0  0.0  11.0        5.0     4.0  

[5 rows x 22 columns]

In [5]:
inputs = df.drop(["Education","Income"],axis = "columns")
inputs.head()

HeartDiseaseorAttack  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   Diabetes  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  AnyHealthcare  \
0       0.0           0.0     0.0      1.0                0.0            1.0   
1       0.0           1.0     0.0      0.0                0.0            0.0   
2       0.0           0.0     1.0      0.0                0.0            1.0   
3       0.0           1.0     1.0      1.0                0.0            1.0   
4       0.0           1.0     1.0      1.0                0.0            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0  
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0  
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0  
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0  
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0

In [6]:
X_train,X_test,y_train,y_test = train_test_split(inputs, df.HeartDiseaseorAttack,test_size=0.3,random_state=21)

In [7]:
# Select

train_size = 2000

X_train = X_train[:train_size]
y_train = y_train[:train_size]

test_size = 400

X_test = X_test[:test_size]
y_test = y_test[:test_size]


In [8]:
# Reduce dimensions
n_dim = 2
pca = PCA(n_components=n_dim).fit(X_train)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
import time
start = time.time()
LR1 =cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), inputs,df.HeartDiseaseorAttack,cv=5)

elapsed = time.time() - start
print(f"Training time: {round(elapsed)} seconds")
print(LR1)

Training time: 10 seconds
[1. 1. 1. 1. 1.]


In [12]:
start = time.time()

SVC1 =cross_val_score(SVC(gamma='auto'),inputs,df.HeartDiseaseorAttack,cv=5)

elapsed = time.time() - start
print(f"Training time: {round(elapsed)} seconds")
print(SVC1)

Training time: 7144 seconds
[0.99773336 0.99729975 0.99795017 0.99793046 0.99741801]


In [15]:
start = time.time()

scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),inputs,df.HeartDiseaseorAttack, cv=5)
np.average(scores1)

elapsed = time.time() - start
print(f"Training time: {round(elapsed)} seconds")
print(scores1)

Training time: 3 seconds
[0.99998029 1.         0.99998029 0.99998029 0.99998029]


In [16]:
scores1

array([0.99998029, 1.        , 0.99998029, 0.99998029, 0.99998029])

In [18]:
start = time.time()

scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),inputs,df.HeartDiseaseorAttack, cv=5)
np.average(scores2)

elapsed = time.time() - start
print(f"Training time: {round(elapsed)} seconds")
print(scores2)

Training time: 9 seconds
[1. 1. 1. 1. 1.]


In [19]:
scores2

array([1., 1., 1., 1., 1.])

In [20]:
start = time.time()

scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),inputs,df.HeartDiseaseorAttack, cv=5)
np.average(scores3)

elapsed = time.time() - start
print(f"Training time: {round(elapsed)} seconds")


Training time: 13 seconds


In [21]:
scores3

array([1., 1., 1., 1., 1.])